### ISSUE TITLE
Combat Tracker - Initiative

### ISSUE THREAD

**Issue by mikitz** [mikitz/wangte#30]
Ability to 

- [ ] Track turns
- [ ] Track rounds
- [ ] Auto-sort Initiative
- [ ] Handle newly added creatures in the middle of combat
- [ ] Send Initiative order to players over SMS/Discord/etc.
